# Generated by Django 4.1.6 on 2023-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_id', models.IntegerField(verbose_name='радио айди')),
                ('radio_name', models.CharField(max_length=30, unique=True, verbose_name='название радио')),
                ('radio_image', models.CharField(max_length=50, verbose_name='картинка радио')),
                ('radio_url', models.URLField(verbose_name='юрл радио')),
                ('genre', models.CharField(max_length=30, verbose_name='жанр')),
                ('country_name', models.CharField(max_length=65, verbose_name='название страны')),
                ('country_id', models.IntegerField(verbose_name='айди страны')),
            ],
        ),
    ]
