# Generated by Django 4.1.6 on 2023-03-09 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_expiration',
            field=models.DateField(default=datetime.date(2027, 3, 8), verbose_name='дата окончания'),
        ),
    ]
