# Generated by Django 4.1.6 on 2023-03-13 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_card_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_expiration',
            field=models.DateField(default=datetime.date(2027, 3, 12), verbose_name='дата окончания'),
        ),
    ]
